detectors:
  UtilityFunction:
    exclude:
      - 'options'
      - 'User'
      - 'api_headers'
  IrresponsibleModule:
    exclude:
      - 'HomePage'
      - 'SignInPage'
      - 'SignUpPage'
      - 'MenuSection'
      - 'User'
      - 'FeatureHelper'
      - 'MyPage'
      - 'ApiWrapper'
  TooManyInstanceVariables:
    exclude:
      - 'User'
  UncommunicativeVariableName:
    exclude:
      - 'User'
  TooManyStatements:
    max_statements: 10
  DuplicateMethodCall:
    exclude:
      - 'sign_up_user'
  FeatureEnvy:
    exclude:
      - 'ApiWrapper'

