# This is the configuration used to check the rubocop source code.

Metrics/BlockLength:
  Max: 35

Metrics/MethodLength:
  Max: 15

Style/MixinUsage:
  Enabled: false

Metrics/AbcSize:
  Enabled: false